### ISSUE TITLE
"Modules" section clarification

### ISSUE THREAD

**Issue by ryanseys** [lukehoban/es6features#54]
The description for modules says the following:

> Implicitly async model – no code executes until requested modules are available and processed.

Wouldn't that be an implicitly synchronous model? Would be great to have this clarified.

**Comment by lukehoban** [comment]
The key thing is that module loading is non-blocking to the JS execution thread.  Since module loading involves IO to resolve module names to program text, the actual execution of a module body is scheduled as a callback for when all the dependencies have been loaded. So module loading is deterministic wrt dependencies, but still scheduled asynchronously on the JS event loop with other code that may already be executing.

**Comment by ryanseys** [comment]
Makes sense! Thanks for the clarification.
